package me.learning.weathernotfound.domain.directGeocoding

import me.learning.weathernotfound.domain.directGeocoding.databaseModels.DirectGeocodingEntity
import me.learning.weathernotfound.domain.directGeocoding.networkModels.DirectGeocodingResponse
import me.learning.weathernotfound.domain.directGeocoding.presentationModels.DirectGeocodingItemModel
import me.learning.weathernotfound.domain.directGeocoding.presentationModels.DirectGeocodingModel
import me.learning.weathernotfound.domain.directGeocoding.presentationModels.LocationCoordinatesModel
import me.learning.weathernotfound.domain.directGeocoding.presentationModels.LocationNamesModel
import me.learning.weathernotfound.utils.Utilities

internal object Converters {

    // Network to Database entity converters
    fun directGeocodingResponseToDirectGeocodingEntity(
        response: DirectGeocodingResponse,
    ): List<DirectGeocodingEntity> {
        val result = mutableListOf<DirectGeocodingEntity>()
        response.forEach { directGeocodingResponseItem ->
            result.add(
                DirectGeocodingEntity(
                    entityId = null,
                    latitude = directGeocodingResponseItem.latitude,
                    longitude = directGeocodingResponseItem.longitude,
                    coordinateName = directGeocodingResponseItem.coordinateName,
                    countryName = directGeocodingResponseItem.countryName,
                    createdAt = Utilities.getCurrentDateTime(),
                    updatedAt = Utilities.getCurrentDateTime(),
                    af = directGeocodingResponseItem.coordinateNameInLanguages.af,
                    am = directGeocodingResponseItem.coordinateNameInLanguages.am,
                    an = directGeocodingResponseItem.coordinateNameInLanguages.an,
                    ar = directGeocodingResponseItem.coordinateNameInLanguages.ar,
                    az = directGeocodingResponseItem.coordinateNameInLanguages.az,
                    ba = directGeocodingResponseItem.coordinateNameInLanguages.ba,
                    be = directGeocodingResponseItem.coordinateNameInLanguages.be,
                    bg = directGeocodingResponseItem.coordinateNameInLanguages.bg,
                    bn = directGeocodingResponseItem.coordinateNameInLanguages.bn,
                    bo = directGeocodingResponseItem.coordinateNameInLanguages.bo,
                    br = directGeocodingResponseItem.coordinateNameInLanguages.br,
                    bs = directGeocodingResponseItem.coordinateNameInLanguages.bs,
                    ca = directGeocodingResponseItem.coordinateNameInLanguages.ca,
                    cs = directGeocodingResponseItem.coordinateNameInLanguages.cs,
                    cv = directGeocodingResponseItem.coordinateNameInLanguages.cv,
                    cy = directGeocodingResponseItem.coordinateNameInLanguages.cy,
                    da = directGeocodingResponseItem.coordinateNameInLanguages.da,
                    de = directGeocodingResponseItem.coordinateNameInLanguages.de,
                    el = directGeocodingResponseItem.coordinateNameInLanguages.el,
                    en = directGeocodingResponseItem.coordinateNameInLanguages.en,
                    eo = directGeocodingResponseItem.coordinateNameInLanguages.eo,
                    es = directGeocodingResponseItem.coordinateNameInLanguages.es,
                    et = directGeocodingResponseItem.coordinateNameInLanguages.et,
                    eu = directGeocodingResponseItem.coordinateNameInLanguages.eu,
                    fa = directGeocodingResponseItem.coordinateNameInLanguages.fa,
                    fi = directGeocodingResponseItem.coordinateNameInLanguages.fi,
                    fo = directGeocodingResponseItem.coordinateNameInLanguages.fo,
                    fr = directGeocodingResponseItem.coordinateNameInLanguages.fr,
                    fy = directGeocodingResponseItem.coordinateNameInLanguages.fy,
                    ga = directGeocodingResponseItem.coordinateNameInLanguages.ga,
                    gd = directGeocodingResponseItem.coordinateNameInLanguages.gd,
                    gl = directGeocodingResponseItem.coordinateNameInLanguages.gl,
                    he = directGeocodingResponseItem.coordinateNameInLanguages.he,
                    hi = directGeocodingResponseItem.coordinateNameInLanguages.hi,
                    hr = directGeocodingResponseItem.coordinateNameInLanguages.hr,
                    ht = directGeocodingResponseItem.coordinateNameInLanguages.ht,
                    hu = directGeocodingResponseItem.coordinateNameInLanguages.hu,
                    hy = directGeocodingResponseItem.coordinateNameInLanguages.hy,
                    ia = directGeocodingResponseItem.coordinateNameInLanguages.ia,
                    id = directGeocodingResponseItem.coordinateNameInLanguages.id,
                    ie = directGeocodingResponseItem.coordinateNameInLanguages.ie,
                    io = directGeocodingResponseItem.coordinateNameInLanguages.io,
                    it = directGeocodingResponseItem.coordinateNameInLanguages.it,
                    ja = directGeocodingResponseItem.coordinateNameInLanguages.ja,
                    ka = directGeocodingResponseItem.coordinateNameInLanguages.ka,
                    kk = directGeocodingResponseItem.coordinateNameInLanguages.kk,
                    kl = directGeocodingResponseItem.coordinateNameInLanguages.kl,
                    kn = directGeocodingResponseItem.coordinateNameInLanguages.kn,
                    ko = directGeocodingResponseItem.coordinateNameInLanguages.ko,
                    ku = directGeocodingResponseItem.coordinateNameInLanguages.ku,
                    kw = directGeocodingResponseItem.coordinateNameInLanguages.kw,
                    lb = directGeocodingResponseItem.coordinateNameInLanguages.lb,
                    lt = directGeocodingResponseItem.coordinateNameInLanguages.lt,
                    lv = directGeocodingResponseItem.coordinateNameInLanguages.lv,
                    mi = directGeocodingResponseItem.coordinateNameInLanguages.mi,
                    mk = directGeocodingResponseItem.coordinateNameInLanguages.mk,
                    ml = directGeocodingResponseItem.coordinateNameInLanguages.ml,
                    mn = directGeocodingResponseItem.coordinateNameInLanguages.mn,
                    mr = directGeocodingResponseItem.coordinateNameInLanguages.mr,
                    ms = directGeocodingResponseItem.coordinateNameInLanguages.ms,
                    my = directGeocodingResponseItem.coordinateNameInLanguages.my,
                    nl = directGeocodingResponseItem.coordinateNameInLanguages.nl,
                    nn = directGeocodingResponseItem.coordinateNameInLanguages.nn,
                    no = directGeocodingResponseItem.coordinateNameInLanguages.no,
                    oc = directGeocodingResponseItem.coordinateNameInLanguages.oc,
                    or = directGeocodingResponseItem.coordinateNameInLanguages.or,
                    os = directGeocodingResponseItem.coordinateNameInLanguages.os,
                    pa = directGeocodingResponseItem.coordinateNameInLanguages.pa,
                    pl = directGeocodingResponseItem.coordinateNameInLanguages.pl,
                    ps = directGeocodingResponseItem.coordinateNameInLanguages.ps,
                    pt = directGeocodingResponseItem.coordinateNameInLanguages.pt,
                    rm = directGeocodingResponseItem.coordinateNameInLanguages.rm,
                    ro = directGeocodingResponseItem.coordinateNameInLanguages.ro,
                    ru = directGeocodingResponseItem.coordinateNameInLanguages.ru,
                    sc = directGeocodingResponseItem.coordinateNameInLanguages.sc,
                    se = directGeocodingResponseItem.coordinateNameInLanguages.se,
                    sk = directGeocodingResponseItem.coordinateNameInLanguages.sk,
                    sl = directGeocodingResponseItem.coordinateNameInLanguages.sl,
                    so = directGeocodingResponseItem.coordinateNameInLanguages.so,
                    sq = directGeocodingResponseItem.coordinateNameInLanguages.sq,
                    sr = directGeocodingResponseItem.coordinateNameInLanguages.sr,
                    sv = directGeocodingResponseItem.coordinateNameInLanguages.sv,
                    sw = directGeocodingResponseItem.coordinateNameInLanguages.sw,
                    ta = directGeocodingResponseItem.coordinateNameInLanguages.ta,
                    te = directGeocodingResponseItem.coordinateNameInLanguages.te,
                    tg = directGeocodingResponseItem.coordinateNameInLanguages.tg,
                    th = directGeocodingResponseItem.coordinateNameInLanguages.th,
                    tk = directGeocodingResponseItem.coordinateNameInLanguages.tk,
                    tl = directGeocodingResponseItem.coordinateNameInLanguages.tl,
                    tr = directGeocodingResponseItem.coordinateNameInLanguages.tr,
                    tt = directGeocodingResponseItem.coordinateNameInLanguages.tt,
                    ug = directGeocodingResponseItem.coordinateNameInLanguages.ug,
                    uk = directGeocodingResponseItem.coordinateNameInLanguages.uk,
                    ur = directGeocodingResponseItem.coordinateNameInLanguages.ur,
                    uz = directGeocodingResponseItem.coordinateNameInLanguages.uz,
                    vi = directGeocodingResponseItem.coordinateNameInLanguages.vi,
                    vo = directGeocodingResponseItem.coordinateNameInLanguages.vo,
                    yi = directGeocodingResponseItem.coordinateNameInLanguages.yi,
                    yo = directGeocodingResponseItem.coordinateNameInLanguages.yo,
                    zh = directGeocodingResponseItem.coordinateNameInLanguages.zh,
                    featureName = directGeocodingResponseItem.coordinateNameInLanguages.featureName,
                    ascii = directGeocodingResponseItem.coordinateNameInLanguages.ascii,
                    ab = directGeocodingResponseItem.coordinateNameInLanguages.ab,
                    av = directGeocodingResponseItem.coordinateNameInLanguages.av,
                    ay = directGeocodingResponseItem.coordinateNameInLanguages.ay,
                    bh = directGeocodingResponseItem.coordinateNameInLanguages.bh,
                    bi = directGeocodingResponseItem.coordinateNameInLanguages.bi,
                    bm = directGeocodingResponseItem.coordinateNameInLanguages.bm,
                    ce = directGeocodingResponseItem.coordinateNameInLanguages.ce,
                    co = directGeocodingResponseItem.coordinateNameInLanguages.co,
                    cr = directGeocodingResponseItem.coordinateNameInLanguages.cr,
                    cu = directGeocodingResponseItem.coordinateNameInLanguages.cu,
                    ee = directGeocodingResponseItem.coordinateNameInLanguages.ee,
                    ff = directGeocodingResponseItem.coordinateNameInLanguages.ff,
                    fj = directGeocodingResponseItem.coordinateNameInLanguages.fj,
                    gn = directGeocodingResponseItem.coordinateNameInLanguages.gn,
                    gu = directGeocodingResponseItem.coordinateNameInLanguages.gu,
                    gv = directGeocodingResponseItem.coordinateNameInLanguages.gv,
                    ha = directGeocodingResponseItem.coordinateNameInLanguages.ha,
                    ig = directGeocodingResponseItem.coordinateNameInLanguages.ig,
                    `is` = directGeocodingResponseItem.coordinateNameInLanguages.`is`,
                    iu = directGeocodingResponseItem.coordinateNameInLanguages.iu,
                    jv = directGeocodingResponseItem.coordinateNameInLanguages.jv,
                    km = directGeocodingResponseItem.coordinateNameInLanguages.km,
                    kv = directGeocodingResponseItem.coordinateNameInLanguages.kv,
                    ky = directGeocodingResponseItem.coordinateNameInLanguages.ky,
                    li = directGeocodingResponseItem.coordinateNameInLanguages.li,
                    ln = directGeocodingResponseItem.coordinateNameInLanguages.ln,
                    lo = directGeocodingResponseItem.coordinateNameInLanguages.lo,
                    mg = directGeocodingResponseItem.coordinateNameInLanguages.mg,
                    mt = directGeocodingResponseItem.coordinateNameInLanguages.mt,
                    na = directGeocodingResponseItem.coordinateNameInLanguages.na,
                    ne = directGeocodingResponseItem.coordinateNameInLanguages.ne,
                    nv = directGeocodingResponseItem.coordinateNameInLanguages.nv,
                    ny = directGeocodingResponseItem.coordinateNameInLanguages.ny,
                    oj = directGeocodingResponseItem.coordinateNameInLanguages.oj,
                    om = directGeocodingResponseItem.coordinateNameInLanguages.om,
                    qu = directGeocodingResponseItem.coordinateNameInLanguages.qu,
                    sa = directGeocodingResponseItem.coordinateNameInLanguages.sa,
                    sd = directGeocodingResponseItem.coordinateNameInLanguages.sd,
                    sh = directGeocodingResponseItem.coordinateNameInLanguages.sh,
                    si = directGeocodingResponseItem.coordinateNameInLanguages.si,
                    sm = directGeocodingResponseItem.coordinateNameInLanguages.sm,
                    sn = directGeocodingResponseItem.coordinateNameInLanguages.sn,
                    st = directGeocodingResponseItem.coordinateNameInLanguages.st,
                    su = directGeocodingResponseItem.coordinateNameInLanguages.su,
                    to = directGeocodingResponseItem.coordinateNameInLanguages.to,
                    tw = directGeocodingResponseItem.coordinateNameInLanguages.tw,
                    wa = directGeocodingResponseItem.coordinateNameInLanguages.wa,
                    wo = directGeocodingResponseItem.coordinateNameInLanguages.wo,
                    zu = directGeocodingResponseItem.coordinateNameInLanguages.zu,
                )
            )
        }
        return result
    }

    // Database to Presentation model converters
    fun directGeocodingEntityToDirectGeocodingModel(
        entities: List<DirectGeocodingEntity>
    ): DirectGeocodingModel {
        val result = mutableListOf<DirectGeocodingItemModel>()
        entities.forEach { entity ->
            result.add(
                DirectGeocodingItemModel(
                    locationName = entity.coordinateName,
                    countryName = entity.countryName,
                    locationCoordinates = LocationCoordinatesModel(
                        latitude = entity.latitude,
                        longitude = entity.longitude,
                    ),
                    locationNameInOtherLanguages = LocationNamesModel(
                        af = entity.af,
                        am = entity.am,
                        an = entity.an,
                        ar = entity.ar,
                        az = entity.az,
                        ba = entity.ba,
                        be = entity.be,
                        bg = entity.bg,
                        bn = entity.bn,
                        bo = entity.bo,
                        br = entity.br,
                        bs = entity.bs,
                        ca = entity.ca,
                        cs = entity.cs,
                        cv = entity.cv,
                        cy = entity.cy,
                        da = entity.da,
                        de = entity.de,
                        el = entity.el,
                        en = entity.en,
                        eo = entity.eo,
                        es = entity.es,
                        et = entity.et,
                        eu = entity.eu,
                        fa = entity.fa,
                        fi = entity.fi,
                        fo = entity.fo,
                        fr = entity.fr,
                        fy = entity.fy,
                        ga = entity.ga,
                        gd = entity.gd,
                        gl = entity.gl,
                        he = entity.he,
                        hi = entity.hi,
                        hr = entity.hr,
                        ht = entity.ht,
                        hu = entity.hu,
                        hy = entity.hy,
                        ia = entity.ia,
                        id = entity.id,
                        ie = entity.ie,
                        io = entity.io,
                        `is` = entity.`is`,
                        it = entity.it,
                        ja = entity.ja,
                        ka = entity.ka,
                        kk = entity.kk,
                        kl = entity.kl,
                        kn = entity.kn,
                        ko = entity.ko,
                        ku = entity.ku,
                        kw = entity.kw,
                        lb = entity.lb,
                        lt = entity.lt,
                        lv = entity.lv,
                        mi = entity.mi,
                        mk = entity.mk,
                        ml = entity.ml,
                        mn = entity.mn,
                        mr = entity.mr,
                        ms = entity.ms,
                        my = entity.my,
                        nl = entity.nl,
                        nn = entity.nn,
                        no = entity.no,
                        oc = entity.oc,
                        or = entity.or,
                        os = entity.os,
                        pa = entity.pa,
                        pl = entity.pl,
                        ps = entity.ps,
                        pt = entity.pt,
                        rm = entity.rm,
                        ro = entity.ro,
                        ru = entity.ru,
                        sc = entity.sc,
                        se = entity.se,
                        sk = entity.sk,
                        sl = entity.sl,
                        so = entity.so,
                        sq = entity.sq,
                        sr = entity.sr,
                        sv = entity.sv,
                        sw = entity.sw,
                        ta = entity.ta,
                        te = entity.te,
                        tg = entity.tg,
                        th = entity.th,
                        tk = entity.tk,
                        tl = entity.tl,
                        tr = entity.tr,
                        tt = entity.tt,
                        ug = entity.ug,
                        uk = entity.uk,
                        ur = entity.ur,
                        uz = entity.uz,
                        vi = entity.vi,
                        vo = entity.vo,
                        yi = entity.yi,
                        yo = entity.yo,
                        zh = entity.zh,
                        featureName = entity.featureName,
                        ascii = entity.ascii,
                        ab = entity.ab,
                        av = entity.av,
                        ay = entity.ay,
                        bh = entity.bh,
                        bi = entity.bi,
                        bm = entity.bm,
                        ce = entity.ce,
                        co = entity.co,
                        cr = entity.cr,
                        cu = entity.cu,
                        ee = entity.ee,
                        ff = entity.ff,
                        fj = entity.fj,
                        gn = entity.gn,
                        gu = entity.gu,
                        gv = entity.gv,
                        ha = entity.ha,
                        ig = entity.ig,
                        iu = entity.iu,
                        jv = entity.jv,
                        km = entity.km,
                        kv = entity.kv,
                        ky = entity.ky,
                        li = entity.li,
                        ln = entity.ln,
                        lo = entity.lo,
                        mg = entity.mg,
                        mt = entity.mt,
                        na = entity.na,
                        ne = entity.ne,
                        nv = entity.nv,
                        ny = entity.ny,
                        oj = entity.oj,
                        om = entity.om,
                        qu = entity.qu,
                        sa = entity.sa,
                        sd = entity.sd,
                        sh = entity.sh,
                        si = entity.si,
                        sm = entity.sm,
                        sn = entity.sn,
                        st = entity.st,
                        su = entity.su,
                        to = entity.to,
                        tw = entity.tw,
                        wa = entity.wa,
                        wo = entity.wo,
                        zu = entity.zu
                    )
                )
            )
        }
        val directGeocodingModel = DirectGeocodingModel()
        directGeocodingModel.addAll(result)
        return directGeocodingModel
    }

    // Network to Presentation model converters
    fun directGeocodingResponseToDirectGeocodingModel(
        response: DirectGeocodingResponse
    ): DirectGeocodingModel {
        val result = mutableListOf<DirectGeocodingItemModel>()
        response.forEach { directGeocodingResponseItem ->
            result.add(
                DirectGeocodingItemModel(
                    locationName = directGeocodingResponseItem.coordinateName,
                    countryName = directGeocodingResponseItem.countryName,
                    locationCoordinates = LocationCoordinatesModel(
                        latitude = directGeocodingResponseItem.latitude,
                        longitude = directGeocodingResponseItem.longitude
                    ),
                    locationNameInOtherLanguages = LocationNamesModel(
                        af = directGeocodingResponseItem.coordinateNameInLanguages.af,
                        am = directGeocodingResponseItem.coordinateNameInLanguages.am,
                        an = directGeocodingResponseItem.coordinateNameInLanguages.an,
                        ar = directGeocodingResponseItem.coordinateNameInLanguages.ar,
                        az = directGeocodingResponseItem.coordinateNameInLanguages.az,
                        ba = directGeocodingResponseItem.coordinateNameInLanguages.ba,
                        be = directGeocodingResponseItem.coordinateNameInLanguages.be,
                        bg = directGeocodingResponseItem.coordinateNameInLanguages.bg,
                        bn = directGeocodingResponseItem.coordinateNameInLanguages.bn,
                        bo = directGeocodingResponseItem.coordinateNameInLanguages.bo,
                        br = directGeocodingResponseItem.coordinateNameInLanguages.br,
                        bs = directGeocodingResponseItem.coordinateNameInLanguages.bs,
                        ca = directGeocodingResponseItem.coordinateNameInLanguages.ca,
                        cs = directGeocodingResponseItem.coordinateNameInLanguages.cs,
                        cv = directGeocodingResponseItem.coordinateNameInLanguages.cv,
                        cy = directGeocodingResponseItem.coordinateNameInLanguages.cy,
                        da = directGeocodingResponseItem.coordinateNameInLanguages.da,
                        de = directGeocodingResponseItem.coordinateNameInLanguages.de,
                        el = directGeocodingResponseItem.coordinateNameInLanguages.el,
                        en = directGeocodingResponseItem.coordinateNameInLanguages.en,
                        eo = directGeocodingResponseItem.coordinateNameInLanguages.eo,
                        es = directGeocodingResponseItem.coordinateNameInLanguages.es,
                        et = directGeocodingResponseItem.coordinateNameInLanguages.et,
                        eu = directGeocodingResponseItem.coordinateNameInLanguages.eu,
                        fa = directGeocodingResponseItem.coordinateNameInLanguages.fa,
                        fi = directGeocodingResponseItem.coordinateNameInLanguages.fi,
                        fo = directGeocodingResponseItem.coordinateNameInLanguages.fo,
                        fr = directGeocodingResponseItem.coordinateNameInLanguages.fr,
                        fy = directGeocodingResponseItem.coordinateNameInLanguages.fy,
                        ga = directGeocodingResponseItem.coordinateNameInLanguages.ga,
                        gd = directGeocodingResponseItem.coordinateNameInLanguages.gd,
                        gl = directGeocodingResponseItem.coordinateNameInLanguages.gl,
                        he = directGeocodingResponseItem.coordinateNameInLanguages.he,
                        hi = directGeocodingResponseItem.coordinateNameInLanguages.hi,
                        hr = directGeocodingResponseItem.coordinateNameInLanguages.hr,
                        ht = directGeocodingResponseItem.coordinateNameInLanguages.ht,
                        hu = directGeocodingResponseItem.coordinateNameInLanguages.hu,
                        hy = directGeocodingResponseItem.coordinateNameInLanguages.hy,
                        ia = directGeocodingResponseItem.coordinateNameInLanguages.ia,
                        id = directGeocodingResponseItem.coordinateNameInLanguages.id,
                        ie = directGeocodingResponseItem.coordinateNameInLanguages.ie,
                        io = directGeocodingResponseItem.coordinateNameInLanguages.io,
                        `is` = directGeocodingResponseItem.coordinateNameInLanguages.`is`,
                        it = directGeocodingResponseItem.coordinateNameInLanguages.it,
                        ja = directGeocodingResponseItem.coordinateNameInLanguages.ja,
                        ka = directGeocodingResponseItem.coordinateNameInLanguages.ka,
                        kk = directGeocodingResponseItem.coordinateNameInLanguages.kk,
                        kl = directGeocodingResponseItem.coordinateNameInLanguages.kl,
                        kn = directGeocodingResponseItem.coordinateNameInLanguages.kn,
                        ko = directGeocodingResponseItem.coordinateNameInLanguages.ko,
                        ku = directGeocodingResponseItem.coordinateNameInLanguages.ku,
                        kw = directGeocodingResponseItem.coordinateNameInLanguages.kw,
                        lb = directGeocodingResponseItem.coordinateNameInLanguages.lb,
                        lt = directGeocodingResponseItem.coordinateNameInLanguages.lt,
                        lv = directGeocodingResponseItem.coordinateNameInLanguages.lv,
                        mi = directGeocodingResponseItem.coordinateNameInLanguages.mi,
                        mk = directGeocodingResponseItem.coordinateNameInLanguages.mk,
                        ml = directGeocodingResponseItem.coordinateNameInLanguages.ml,
                        mn = directGeocodingResponseItem.coordinateNameInLanguages.mn,
                        mr = directGeocodingResponseItem.coordinateNameInLanguages.mr,
                        ms = directGeocodingResponseItem.coordinateNameInLanguages.ms,
                        my = directGeocodingResponseItem.coordinateNameInLanguages.my,
                        nl = directGeocodingResponseItem.coordinateNameInLanguages.nl,
                        nn = directGeocodingResponseItem.coordinateNameInLanguages.nn,
                        no = directGeocodingResponseItem.coordinateNameInLanguages.no,
                        oc = directGeocodingResponseItem.coordinateNameInLanguages.oc,
                        or = directGeocodingResponseItem.coordinateNameInLanguages.or,
                        os = directGeocodingResponseItem.coordinateNameInLanguages.os,
                        pa = directGeocodingResponseItem.coordinateNameInLanguages.pa,
                        pl = directGeocodingResponseItem.coordinateNameInLanguages.pl,
                        ps = directGeocodingResponseItem.coordinateNameInLanguages.ps,
                        pt = directGeocodingResponseItem.coordinateNameInLanguages.pt,
                        rm = directGeocodingResponseItem.coordinateNameInLanguages.rm,
                        ro = directGeocodingResponseItem.coordinateNameInLanguages.ro,
                        ru = directGeocodingResponseItem.coordinateNameInLanguages.ru,
                        sc = directGeocodingResponseItem.coordinateNameInLanguages.sc,
                        se = directGeocodingResponseItem.coordinateNameInLanguages.se,
                        sk = directGeocodingResponseItem.coordinateNameInLanguages.sk,
                        sl = directGeocodingResponseItem.coordinateNameInLanguages.sl,
                        so = directGeocodingResponseItem.coordinateNameInLanguages.so,
                        sq = directGeocodingResponseItem.coordinateNameInLanguages.sq,
                        sr = directGeocodingResponseItem.coordinateNameInLanguages.sr,
                        sv = directGeocodingResponseItem.coordinateNameInLanguages.sv,
                        sw = directGeocodingResponseItem.coordinateNameInLanguages.sw,
                        ta = directGeocodingResponseItem.coordinateNameInLanguages.ta,
                        te = directGeocodingResponseItem.coordinateNameInLanguages.te,
                        tg = directGeocodingResponseItem.coordinateNameInLanguages.tg,
                        th = directGeocodingResponseItem.coordinateNameInLanguages.th,
                        tk = directGeocodingResponseItem.coordinateNameInLanguages.tk,
                        tl = directGeocodingResponseItem.coordinateNameInLanguages.tl,
                        tr = directGeocodingResponseItem.coordinateNameInLanguages.tr,
                        tt = directGeocodingResponseItem.coordinateNameInLanguages.tt,
                        ug = directGeocodingResponseItem.coordinateNameInLanguages.ug,
                        uk = directGeocodingResponseItem.coordinateNameInLanguages.uk,
                        ur = directGeocodingResponseItem.coordinateNameInLanguages.ur,
                        uz = directGeocodingResponseItem.coordinateNameInLanguages.uz,
                        vi = directGeocodingResponseItem.coordinateNameInLanguages.vi,
                        vo = directGeocodingResponseItem.coordinateNameInLanguages.vo,
                        yi = directGeocodingResponseItem.coordinateNameInLanguages.yi,
                        yo = directGeocodingResponseItem.coordinateNameInLanguages.yo,
                        zh = directGeocodingResponseItem.coordinateNameInLanguages.zh,
                        featureName = directGeocodingResponseItem.coordinateNameInLanguages.featureName,
                        ascii = directGeocodingResponseItem.coordinateNameInLanguages.ascii,
                        ab = directGeocodingResponseItem.coordinateNameInLanguages.ab,
                        av = directGeocodingResponseItem.coordinateNameInLanguages.av,
                        ay = directGeocodingResponseItem.coordinateNameInLanguages.ay,
                        bh = directGeocodingResponseItem.coordinateNameInLanguages.bh,
                        bi = directGeocodingResponseItem.coordinateNameInLanguages.bi,
                        bm = directGeocodingResponseItem.coordinateNameInLanguages.bm,
                        ce = directGeocodingResponseItem.coordinateNameInLanguages.ce,
                        co = directGeocodingResponseItem.coordinateNameInLanguages.co,
                        cr = directGeocodingResponseItem.coordinateNameInLanguages.cr,
                        cu = directGeocodingResponseItem.coordinateNameInLanguages.cu,
                        ee = directGeocodingResponseItem.coordinateNameInLanguages.ee,
                        ff = directGeocodingResponseItem.coordinateNameInLanguages.ff,
                        fj = directGeocodingResponseItem.coordinateNameInLanguages.fj,
                        gn = directGeocodingResponseItem.coordinateNameInLanguages.gn,
                        gu = directGeocodingResponseItem.coordinateNameInLanguages.gu,
                        gv = directGeocodingResponseItem.coordinateNameInLanguages.gv,
                        ha = directGeocodingResponseItem.coordinateNameInLanguages.ha,
                        ig = directGeocodingResponseItem.coordinateNameInLanguages.ig,
                        iu = directGeocodingResponseItem.coordinateNameInLanguages.iu,
                        jv = directGeocodingResponseItem.coordinateNameInLanguages.jv,
                        km = directGeocodingResponseItem.coordinateNameInLanguages.km,
                        kv = directGeocodingResponseItem.coordinateNameInLanguages.kv,
                        ky = directGeocodingResponseItem.coordinateNameInLanguages.ky,
                        li = directGeocodingResponseItem.coordinateNameInLanguages.li,
                        ln = directGeocodingResponseItem.coordinateNameInLanguages.ln,
                        lo = directGeocodingResponseItem.coordinateNameInLanguages.lo,
                        mg = directGeocodingResponseItem.coordinateNameInLanguages.mg,
                        mt = directGeocodingResponseItem.coordinateNameInLanguages.mt,
                        na = directGeocodingResponseItem.coordinateNameInLanguages.na,
                        ne = directGeocodingResponseItem.coordinateNameInLanguages.ne,
                        nv = directGeocodingResponseItem.coordinateNameInLanguages.nv,
                        ny = directGeocodingResponseItem.coordinateNameInLanguages.ny,
                        oj = directGeocodingResponseItem.coordinateNameInLanguages.oj,
                        om = directGeocodingResponseItem.coordinateNameInLanguages.om,
                        qu = directGeocodingResponseItem.coordinateNameInLanguages.qu,
                        sa = directGeocodingResponseItem.coordinateNameInLanguages.sa,
                        sd = directGeocodingResponseItem.coordinateNameInLanguages.sd,
                        sh = directGeocodingResponseItem.coordinateNameInLanguages.sh,
                        si = directGeocodingResponseItem.coordinateNameInLanguages.si,
                        sm = directGeocodingResponseItem.coordinateNameInLanguages.sm,
                        sn = directGeocodingResponseItem.coordinateNameInLanguages.sn,
                        st = directGeocodingResponseItem.coordinateNameInLanguages.st,
                        su = directGeocodingResponseItem.coordinateNameInLanguages.su,
                        to = directGeocodingResponseItem.coordinateNameInLanguages.to,
                        tw = directGeocodingResponseItem.coordinateNameInLanguages.tw,
                        wa = directGeocodingResponseItem.coordinateNameInLanguages.wa,
                        wo = directGeocodingResponseItem.coordinateNameInLanguages.wo,
                        zu = directGeocodingResponseItem.coordinateNameInLanguages.zu,
                    )
                )
            )
        }
        val directGeocodingModel = DirectGeocodingModel()
        directGeocodingModel.addAll(result)
        return directGeocodingModel
    }
}
