package me.learning.weathernotfound.domain.reverseGeocoding

import me.learning.weathernotfound.domain.reverseGeocoding.databaseModels.ReverseGeocodingEntity
import me.learning.weathernotfound.domain.reverseGeocoding.networkModels.ReversGeocodingResponse
import me.learning.weathernotfound.domain.reverseGeocoding.presentationModels.LocationCoordinatesModel
import me.learning.weathernotfound.domain.reverseGeocoding.presentationModels.LocationNamesModel
import me.learning.weathernotfound.domain.reverseGeocoding.presentationModels.ReverseGeocodingItemModel
import me.learning.weathernotfound.domain.reverseGeocoding.presentationModels.ReverseGeocodingModel
import me.learning.weathernotfound.utils.Utilities

internal object Converters {

    // Network to Database entity converters
    fun reverseGeocodingResponseToReverseGeocodingEntity(
        response: ReversGeocodingResponse,
        entityId: Long? = null,
    ): List<ReverseGeocodingEntity> {
        val result = mutableListOf<ReverseGeocodingEntity>()
        response.forEach { reverseGeocodingResponseItem ->
            result.add(
                ReverseGeocodingEntity(
                    entityId = entityId,
                    latitude = reverseGeocodingResponseItem.latitude,
                    longitude = reverseGeocodingResponseItem.longitude,
                    coordinateName = reverseGeocodingResponseItem.coordinateName,
                    countryName = reverseGeocodingResponseItem.countryName,
                    createdAt = Utilities.getCurrentDateTime(),
                    updatedAt = Utilities.getCurrentDateTime(),
                    af = reverseGeocodingResponseItem.coordinateNameInLanguages.af,
                    am = reverseGeocodingResponseItem.coordinateNameInLanguages.am,
                    an = reverseGeocodingResponseItem.coordinateNameInLanguages.an,
                    ar = reverseGeocodingResponseItem.coordinateNameInLanguages.ar,
                    az = reverseGeocodingResponseItem.coordinateNameInLanguages.az,
                    ba = reverseGeocodingResponseItem.coordinateNameInLanguages.ba,
                    be = reverseGeocodingResponseItem.coordinateNameInLanguages.be,
                    bg = reverseGeocodingResponseItem.coordinateNameInLanguages.bg,
                    bn = reverseGeocodingResponseItem.coordinateNameInLanguages.bn,
                    bo = reverseGeocodingResponseItem.coordinateNameInLanguages.bo,
                    br = reverseGeocodingResponseItem.coordinateNameInLanguages.br,
                    bs = reverseGeocodingResponseItem.coordinateNameInLanguages.bs,
                    ca = reverseGeocodingResponseItem.coordinateNameInLanguages.ca,
                    cs = reverseGeocodingResponseItem.coordinateNameInLanguages.cs,
                    cv = reverseGeocodingResponseItem.coordinateNameInLanguages.cv,
                    cy = reverseGeocodingResponseItem.coordinateNameInLanguages.cy,
                    da = reverseGeocodingResponseItem.coordinateNameInLanguages.da,
                    de = reverseGeocodingResponseItem.coordinateNameInLanguages.de,
                    el = reverseGeocodingResponseItem.coordinateNameInLanguages.el,
                    en = reverseGeocodingResponseItem.coordinateNameInLanguages.en,
                    eo = reverseGeocodingResponseItem.coordinateNameInLanguages.eo,
                    es = reverseGeocodingResponseItem.coordinateNameInLanguages.es,
                    et = reverseGeocodingResponseItem.coordinateNameInLanguages.et,
                    eu = reverseGeocodingResponseItem.coordinateNameInLanguages.eu,
                    fa = reverseGeocodingResponseItem.coordinateNameInLanguages.fa,
                    fi = reverseGeocodingResponseItem.coordinateNameInLanguages.fi,
                    fo = reverseGeocodingResponseItem.coordinateNameInLanguages.fo,
                    fr = reverseGeocodingResponseItem.coordinateNameInLanguages.fr,
                    fy = reverseGeocodingResponseItem.coordinateNameInLanguages.fy,
                    ga = reverseGeocodingResponseItem.coordinateNameInLanguages.ga,
                    gd = reverseGeocodingResponseItem.coordinateNameInLanguages.gd,
                    gl = reverseGeocodingResponseItem.coordinateNameInLanguages.gl,
                    he = reverseGeocodingResponseItem.coordinateNameInLanguages.he,
                    hi = reverseGeocodingResponseItem.coordinateNameInLanguages.hi,
                    hr = reverseGeocodingResponseItem.coordinateNameInLanguages.hr,
                    ht = reverseGeocodingResponseItem.coordinateNameInLanguages.ht,
                    hu = reverseGeocodingResponseItem.coordinateNameInLanguages.hu,
                    hy = reverseGeocodingResponseItem.coordinateNameInLanguages.hy,
                    ia = reverseGeocodingResponseItem.coordinateNameInLanguages.ia,
                    id = reverseGeocodingResponseItem.coordinateNameInLanguages.id,
                    ie = reverseGeocodingResponseItem.coordinateNameInLanguages.ie,
                    io = reverseGeocodingResponseItem.coordinateNameInLanguages.io,
                    /* is = */ reverseGeocodingResponseItem.coordinateNameInLanguages.`is`,
                    it = reverseGeocodingResponseItem.coordinateNameInLanguages.it,
                    ja = reverseGeocodingResponseItem.coordinateNameInLanguages.ja,
                    ka = reverseGeocodingResponseItem.coordinateNameInLanguages.ka,
                    kk = reverseGeocodingResponseItem.coordinateNameInLanguages.kk,
                    kl = reverseGeocodingResponseItem.coordinateNameInLanguages.kl,
                    kn = reverseGeocodingResponseItem.coordinateNameInLanguages.kn,
                    ko = reverseGeocodingResponseItem.coordinateNameInLanguages.ko,
                    ku = reverseGeocodingResponseItem.coordinateNameInLanguages.ku,
                    kw = reverseGeocodingResponseItem.coordinateNameInLanguages.kw,
                    la = reverseGeocodingResponseItem.coordinateNameInLanguages.la,
                    lb = reverseGeocodingResponseItem.coordinateNameInLanguages.lb,
                    lt = reverseGeocodingResponseItem.coordinateNameInLanguages.lt,
                    lv = reverseGeocodingResponseItem.coordinateNameInLanguages.lv,
                    mi = reverseGeocodingResponseItem.coordinateNameInLanguages.mi,
                    mk = reverseGeocodingResponseItem.coordinateNameInLanguages.mk,
                    ml = reverseGeocodingResponseItem.coordinateNameInLanguages.ml,
                    mn = reverseGeocodingResponseItem.coordinateNameInLanguages.mn,
                    mr = reverseGeocodingResponseItem.coordinateNameInLanguages.mr,
                    ms = reverseGeocodingResponseItem.coordinateNameInLanguages.ms,
                    my = reverseGeocodingResponseItem.coordinateNameInLanguages.my,
                    nl = reverseGeocodingResponseItem.coordinateNameInLanguages.nl,
                    nn = reverseGeocodingResponseItem.coordinateNameInLanguages.nn,
                    no = reverseGeocodingResponseItem.coordinateNameInLanguages.no,
                    oc = reverseGeocodingResponseItem.coordinateNameInLanguages.oc,
                    or = reverseGeocodingResponseItem.coordinateNameInLanguages.or,
                    os = reverseGeocodingResponseItem.coordinateNameInLanguages.os,
                    pa = reverseGeocodingResponseItem.coordinateNameInLanguages.pa,
                    pl = reverseGeocodingResponseItem.coordinateNameInLanguages.pl,
                    ps = reverseGeocodingResponseItem.coordinateNameInLanguages.ps,
                    pt = reverseGeocodingResponseItem.coordinateNameInLanguages.pt,
                    rm = reverseGeocodingResponseItem.coordinateNameInLanguages.rm,
                    ro = reverseGeocodingResponseItem.coordinateNameInLanguages.ro,
                    ru = reverseGeocodingResponseItem.coordinateNameInLanguages.ru,
                    sc = reverseGeocodingResponseItem.coordinateNameInLanguages.sc,
                    se = reverseGeocodingResponseItem.coordinateNameInLanguages.se,
                    sk = reverseGeocodingResponseItem.coordinateNameInLanguages.sk,
                    sl = reverseGeocodingResponseItem.coordinateNameInLanguages.sl,
                    so = reverseGeocodingResponseItem.coordinateNameInLanguages.so,
                    sq = reverseGeocodingResponseItem.coordinateNameInLanguages.sq,
                    sr = reverseGeocodingResponseItem.coordinateNameInLanguages.sr,
                    sv = reverseGeocodingResponseItem.coordinateNameInLanguages.sv,
                    sw = reverseGeocodingResponseItem.coordinateNameInLanguages.sw,
                    ta = reverseGeocodingResponseItem.coordinateNameInLanguages.ta,
                    te = reverseGeocodingResponseItem.coordinateNameInLanguages.te,
                    tg = reverseGeocodingResponseItem.coordinateNameInLanguages.tg,
                    th = reverseGeocodingResponseItem.coordinateNameInLanguages.th,
                    tk = reverseGeocodingResponseItem.coordinateNameInLanguages.tk,
                    tl = reverseGeocodingResponseItem.coordinateNameInLanguages.tl,
                    tr = reverseGeocodingResponseItem.coordinateNameInLanguages.tr,
                    tt = reverseGeocodingResponseItem.coordinateNameInLanguages.tt,
                    ug = reverseGeocodingResponseItem.coordinateNameInLanguages.ug,
                    uk = reverseGeocodingResponseItem.coordinateNameInLanguages.uk,
                    ur = reverseGeocodingResponseItem.coordinateNameInLanguages.ur,
                    uz = reverseGeocodingResponseItem.coordinateNameInLanguages.uz,
                    vi = reverseGeocodingResponseItem.coordinateNameInLanguages.vi,
                    vo = reverseGeocodingResponseItem.coordinateNameInLanguages.vo,
                    yi = reverseGeocodingResponseItem.coordinateNameInLanguages.yi,
                    yo = reverseGeocodingResponseItem.coordinateNameInLanguages.yo,
                    zh = reverseGeocodingResponseItem.coordinateNameInLanguages.zh,
                    featureName = reverseGeocodingResponseItem.coordinateNameInLanguages.featureName,
                    ascii = reverseGeocodingResponseItem.coordinateNameInLanguages.ascii,
                )
            )
        }
        return result
    }

    // Database to Presentation model converters
    fun reverseGeocodingEntitiesToReverseGeocodingModel(
        entities: List<ReverseGeocodingEntity>
    ): ReverseGeocodingModel {
        val result = mutableListOf<ReverseGeocodingItemModel>()
        entities.forEach { entity ->
            result.add(
                ReverseGeocodingItemModel(
                    locationName = entity.coordinateName,
                    countryName = entity.countryName,
                    locationCoordinates = LocationCoordinatesModel(
                        latitude = entity.latitude,
                        longitude = entity.longitude,
                    ),
                    locationNameInOtherLanguages = LocationNamesModel(
                        af = entity.af,
                        am = entity.am,
                        an = entity.an,
                        ar = entity.ar,
                        az = entity.az,
                        ba = entity.ba,
                        be = entity.be,
                        bg = entity.bg,
                        bn = entity.bn,
                        bo = entity.bo,
                        br = entity.br,
                        bs = entity.bs,
                        ca = entity.ca,
                        cs = entity.cs,
                        cv = entity.cv,
                        cy = entity.cy,
                        da = entity.da,
                        de = entity.de,
                        el = entity.el,
                        en = entity.en,
                        eo = entity.eo,
                        es = entity.es,
                        et = entity.et,
                        eu = entity.eu,
                        fa = entity.fa,
                        fi = entity.fi,
                        fo = entity.fo,
                        fr = entity.fr,
                        fy = entity.fy,
                        ga = entity.ga,
                        gd = entity.gd,
                        gl = entity.gl,
                        he = entity.he,
                        hi = entity.hi,
                        hr = entity.hr,
                        ht = entity.ht,
                        hu = entity.hu,
                        hy = entity.hy,
                        ia = entity.ia,
                        id = entity.id,
                        ie = entity.ie,
                        io = entity.io,
                        /* is = */ entity.`is`,
                        it = entity.it,
                        ja = entity.ja,
                        ka = entity.ka,
                        kk = entity.kk,
                        kl = entity.kl,
                        kn = entity.kn,
                        ko = entity.ko,
                        ku = entity.ku,
                        kw = entity.kw,
                        la = entity.la,
                        lb = entity.lb,
                        lt = entity.lt,
                        lv = entity.lv,
                        mi = entity.mi,
                        mk = entity.mk,
                        ml = entity.ml,
                        mn = entity.mn,
                        mr = entity.mr,
                        ms = entity.ms,
                        my = entity.my,
                        nl = entity.nl,
                        nn = entity.nn,
                        no = entity.no,
                        oc = entity.oc,
                        or = entity.or,
                        os = entity.os,
                        pa = entity.pa,
                        pl = entity.pl,
                        ps = entity.ps,
                        pt = entity.pt,
                        rm = entity.rm,
                        ro = entity.ro,
                        ru = entity.ru,
                        sc = entity.sc,
                        se = entity.se,
                        sk = entity.sk,
                        sl = entity.sl,
                        so = entity.so,
                        sq = entity.sq,
                        sr = entity.sr,
                        sv = entity.sv,
                        sw = entity.sw,
                        ta = entity.ta,
                        te = entity.te,
                        tg = entity.tg,
                        th = entity.th,
                        tk = entity.tk,
                        tl = entity.tl,
                        tr = entity.tr,
                        tt = entity.tt,
                        ug = entity.ug,
                        uk = entity.uk,
                        ur = entity.ur,
                        uz = entity.uz,
                        vi = entity.vi,
                        vo = entity.vo,
                        yi = entity.yi,
                        yo = entity.yo,
                        zh = entity.zh,
                        featureName = entity.featureName,
                        ascii = entity.ascii,
                    )
                )
            )
        }
        val reverseGeocodingModel = ReverseGeocodingModel()
        reverseGeocodingModel.addAll(result)
        return reverseGeocodingModel
    }

    // Network to Presentation model converters
    fun reverseGeocodingResponseToLocationInfoModel(
        response: ReversGeocodingResponse
    ): ReverseGeocodingModel {
        val result = mutableListOf<ReverseGeocodingItemModel>()
        response.forEach { reverseGeocodingResponseItem ->
            result.add(
                ReverseGeocodingItemModel(
                    locationName = reverseGeocodingResponseItem.coordinateName,
                    countryName = reverseGeocodingResponseItem.countryName,
                    locationCoordinates = LocationCoordinatesModel(
                        latitude = reverseGeocodingResponseItem.latitude,
                        longitude = reverseGeocodingResponseItem.longitude
                    ),
                    locationNameInOtherLanguages = LocationNamesModel(
                        af = reverseGeocodingResponseItem.coordinateNameInLanguages.af,
                        am = reverseGeocodingResponseItem.coordinateNameInLanguages.am,
                        an = reverseGeocodingResponseItem.coordinateNameInLanguages.an,
                        ar = reverseGeocodingResponseItem.coordinateNameInLanguages.ar,
                        az = reverseGeocodingResponseItem.coordinateNameInLanguages.az,
                        ba = reverseGeocodingResponseItem.coordinateNameInLanguages.ba,
                        be = reverseGeocodingResponseItem.coordinateNameInLanguages.be,
                        bg = reverseGeocodingResponseItem.coordinateNameInLanguages.bg,
                        bn = reverseGeocodingResponseItem.coordinateNameInLanguages.bn,
                        bo = reverseGeocodingResponseItem.coordinateNameInLanguages.bo,
                        br = reverseGeocodingResponseItem.coordinateNameInLanguages.br,
                        bs = reverseGeocodingResponseItem.coordinateNameInLanguages.bs,
                        ca = reverseGeocodingResponseItem.coordinateNameInLanguages.ca,
                        cs = reverseGeocodingResponseItem.coordinateNameInLanguages.cs,
                        cv = reverseGeocodingResponseItem.coordinateNameInLanguages.cv,
                        cy = reverseGeocodingResponseItem.coordinateNameInLanguages.cy,
                        da = reverseGeocodingResponseItem.coordinateNameInLanguages.da,
                        de = reverseGeocodingResponseItem.coordinateNameInLanguages.de,
                        el = reverseGeocodingResponseItem.coordinateNameInLanguages.el,
                        en = reverseGeocodingResponseItem.coordinateNameInLanguages.en,
                        eo = reverseGeocodingResponseItem.coordinateNameInLanguages.eo,
                        es = reverseGeocodingResponseItem.coordinateNameInLanguages.es,
                        et = reverseGeocodingResponseItem.coordinateNameInLanguages.et,
                        eu = reverseGeocodingResponseItem.coordinateNameInLanguages.eu,
                        fa = reverseGeocodingResponseItem.coordinateNameInLanguages.fa,
                        fi = reverseGeocodingResponseItem.coordinateNameInLanguages.fi,
                        fo = reverseGeocodingResponseItem.coordinateNameInLanguages.fo,
                        fr = reverseGeocodingResponseItem.coordinateNameInLanguages.fr,
                        fy = reverseGeocodingResponseItem.coordinateNameInLanguages.fy,
                        ga = reverseGeocodingResponseItem.coordinateNameInLanguages.ga,
                        gd = reverseGeocodingResponseItem.coordinateNameInLanguages.gd,
                        gl = reverseGeocodingResponseItem.coordinateNameInLanguages.gl,
                        he = reverseGeocodingResponseItem.coordinateNameInLanguages.he,
                        hi = reverseGeocodingResponseItem.coordinateNameInLanguages.hi,
                        hr = reverseGeocodingResponseItem.coordinateNameInLanguages.hr,
                        ht = reverseGeocodingResponseItem.coordinateNameInLanguages.ht,
                        hu = reverseGeocodingResponseItem.coordinateNameInLanguages.hu,
                        hy = reverseGeocodingResponseItem.coordinateNameInLanguages.hy,
                        ia = reverseGeocodingResponseItem.coordinateNameInLanguages.ia,
                        id = reverseGeocodingResponseItem.coordinateNameInLanguages.id,
                        ie = reverseGeocodingResponseItem.coordinateNameInLanguages.ie,
                        io = reverseGeocodingResponseItem.coordinateNameInLanguages.io,
                        /* is = */ reverseGeocodingResponseItem.coordinateNameInLanguages.`is`,
                        it = reverseGeocodingResponseItem.coordinateNameInLanguages.it,
                        ja = reverseGeocodingResponseItem.coordinateNameInLanguages.ja,
                        ka = reverseGeocodingResponseItem.coordinateNameInLanguages.ka,
                        kk = reverseGeocodingResponseItem.coordinateNameInLanguages.kk,
                        kl = reverseGeocodingResponseItem.coordinateNameInLanguages.kl,
                        kn = reverseGeocodingResponseItem.coordinateNameInLanguages.kn,
                        ko = reverseGeocodingResponseItem.coordinateNameInLanguages.ko,
                        ku = reverseGeocodingResponseItem.coordinateNameInLanguages.ku,
                        kw = reverseGeocodingResponseItem.coordinateNameInLanguages.kw,
                        la = reverseGeocodingResponseItem.coordinateNameInLanguages.la,
                        lb = reverseGeocodingResponseItem.coordinateNameInLanguages.lb,
                        lt = reverseGeocodingResponseItem.coordinateNameInLanguages.lt,
                        lv = reverseGeocodingResponseItem.coordinateNameInLanguages.lv,
                        mi = reverseGeocodingResponseItem.coordinateNameInLanguages.mi,
                        mk = reverseGeocodingResponseItem.coordinateNameInLanguages.mk,
                        ml = reverseGeocodingResponseItem.coordinateNameInLanguages.ml,
                        mn = reverseGeocodingResponseItem.coordinateNameInLanguages.mn,
                        mr = reverseGeocodingResponseItem.coordinateNameInLanguages.mr,
                        ms = reverseGeocodingResponseItem.coordinateNameInLanguages.ms,
                        my = reverseGeocodingResponseItem.coordinateNameInLanguages.my,
                        nl = reverseGeocodingResponseItem.coordinateNameInLanguages.nl,
                        nn = reverseGeocodingResponseItem.coordinateNameInLanguages.nn,
                        no = reverseGeocodingResponseItem.coordinateNameInLanguages.no,
                        oc = reverseGeocodingResponseItem.coordinateNameInLanguages.oc,
                        or = reverseGeocodingResponseItem.coordinateNameInLanguages.or,
                        os = reverseGeocodingResponseItem.coordinateNameInLanguages.os,
                        pa = reverseGeocodingResponseItem.coordinateNameInLanguages.pa,
                        pl = reverseGeocodingResponseItem.coordinateNameInLanguages.pl,
                        ps = reverseGeocodingResponseItem.coordinateNameInLanguages.ps,
                        pt = reverseGeocodingResponseItem.coordinateNameInLanguages.pt,
                        rm = reverseGeocodingResponseItem.coordinateNameInLanguages.rm,
                        ro = reverseGeocodingResponseItem.coordinateNameInLanguages.ro,
                        ru = reverseGeocodingResponseItem.coordinateNameInLanguages.ru,
                        sc = reverseGeocodingResponseItem.coordinateNameInLanguages.sc,
                        se = reverseGeocodingResponseItem.coordinateNameInLanguages.se,
                        sk = reverseGeocodingResponseItem.coordinateNameInLanguages.sk,
                        sl = reverseGeocodingResponseItem.coordinateNameInLanguages.sl,
                        so = reverseGeocodingResponseItem.coordinateNameInLanguages.so,
                        sq = reverseGeocodingResponseItem.coordinateNameInLanguages.sq,
                        sr = reverseGeocodingResponseItem.coordinateNameInLanguages.sr,
                        sv = reverseGeocodingResponseItem.coordinateNameInLanguages.sv,
                        sw = reverseGeocodingResponseItem.coordinateNameInLanguages.sw,
                        ta = reverseGeocodingResponseItem.coordinateNameInLanguages.ta,
                        te = reverseGeocodingResponseItem.coordinateNameInLanguages.te,
                        tg = reverseGeocodingResponseItem.coordinateNameInLanguages.tg,
                        th = reverseGeocodingResponseItem.coordinateNameInLanguages.th,
                        tk = reverseGeocodingResponseItem.coordinateNameInLanguages.tk,
                        tl = reverseGeocodingResponseItem.coordinateNameInLanguages.tl,
                        tr = reverseGeocodingResponseItem.coordinateNameInLanguages.tr,
                        tt = reverseGeocodingResponseItem.coordinateNameInLanguages.tt,
                        ug = reverseGeocodingResponseItem.coordinateNameInLanguages.ug,
                        uk = reverseGeocodingResponseItem.coordinateNameInLanguages.uk,
                        ur = reverseGeocodingResponseItem.coordinateNameInLanguages.ur,
                        uz = reverseGeocodingResponseItem.coordinateNameInLanguages.uz,
                        vi = reverseGeocodingResponseItem.coordinateNameInLanguages.vi,
                        vo = reverseGeocodingResponseItem.coordinateNameInLanguages.vo,
                        yi = reverseGeocodingResponseItem.coordinateNameInLanguages.yi,
                        yo = reverseGeocodingResponseItem.coordinateNameInLanguages.yo,
                        zh = reverseGeocodingResponseItem.coordinateNameInLanguages.zh,
                        featureName = reverseGeocodingResponseItem.coordinateNameInLanguages.featureName,
                        ascii = reverseGeocodingResponseItem.coordinateNameInLanguages.ascii,
                    )
                )
            )
        }
        val reverseGeocodingModel = ReverseGeocodingModel()
        reverseGeocodingModel.addAll(result)
        return reverseGeocodingModel
    }
}
